# Name of your application. Used to uniquely configure containers.
service: bouldering

# Name of the container image.
image: astaxanthin/bouldering

# Deploy to these servers.
servers:
  web:
    - 16.176.165.26

# Disable health checks
healthcheck:
  disable: true

# Credentials for your image host.
registry:
  username: astaxanthin
  password:
    - KAMAL_REGISTRY_PASSWORD

# Inject ENV variables into containers (secrets come from .kamal/secrets).
env:
  secret:
    - RAILS_MASTER_KEY
  clear:
    WEB_CONCURRENCY: 2

# Use a persistent storage volume for sqlite database files and local Active Storage files.
volumes:
  - "bouldering_storage:/rails/storage"

# Configure the image builder.
builder:
  arch: amd64

# Use a different ssh user than root
ssh:
  user: ubuntu
  keys:
    - ~/.ssh/bouldering-key.pem
